name: Build and Publish

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  update_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name : update lists
        shell: bash
        run : |
          bash getip.sh
      - name: push updated lists
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update-lists
